const userText = prompt('Введите текст').trim()
const wordFromText = prompt('Введите слово из текста').trim()
const indexOfWord = userText.indexOf(wordFromText)
const str = userText.slice(0, indexOfWord)
console.log(userText)
console.log(indexOfWord)
console.log(str)
